### ISSUE TITLE
バグ：裏のみを入れて、デザイン再編集をした場合にデザインを動かさないとデザインありとみなされない

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#1003]
バグ：裏のみを入れて、デザイン再編集をした場合にデザインを動かさないとデザインありとみなされない

**Comment by alexeypolitov** [comment]
@tomoyuki1110 確認しましたが問題が発生してないです。動画でも撮っていただけますか？

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました。ご確認ください
