### ISSUE TITLE
スポーツTシャツのプレビューのカラーがおかしい

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#1004]
プレビューでもそのまま
![screenshot_20170608-085449](https://user-images.githubusercontent.com/17405609/26906459-53591fe0-4c28-11e7-8ada-f202317b8861.png)
![screenshot_20170608-085441](https://user-images.githubusercontent.com/17405609/26906462-57e76e72-4c28-11e7-984f-c420194e6af7.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 DBで以前からこういう画像が登録されてます
