### ISSUE TITLE
アイテム名をだす

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#1005]
デザインでツール上に
![project capture 5](https://user-images.githubusercontent.com/17405609/26938478-4b1f0fba-4caf-11e7-95f4-5ffab8c42d0f.jpg)
アイテム名をだしたい

しかくの枠のあるところでいいのでお願いします。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 ベータ版で追加しました。ご確認ください。
