### ISSUE TITLE
アップロード時間をさらにスピードアップ

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#1006]
最近のカメラは撮ったら5mb以上になる。
現在の仕様だと5mb以上は異常に重いので
追加料金でもよいので、今より大幅にスピードアップしてほしい。

**Comment by tomoyuki1110** [comment]
調べたら1mbも遅くなってました。
アンドロイドexperia 4gで確認。
他のメディアでも確認して遅かったので遅いのだと思います。

スラックに動画をアップロードしました。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 スピードアップしました。ご確認ください
