### ISSUE TITLE
iphoeサファリ使用でテキストバグ

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#1012]
下記のような画像をテキストで作ったら
カートに入れたときに数字や名前が消える。
注文前でこちらで試してもおきました。
![screenshot_20170620-143900](https://user-images.githubusercontent.com/17405609/27318249-6c446c92-55c6-11e7-8f9d-3309ba51d3cf.png)

修正お願いします。
特にiphoneなので問題です。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました
