### ISSUE TITLE
テキストバグ

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#1013]
テキストで切れるバグです。
320の文字が切れてます。
![screenshot_20170620-144227](https://user-images.githubusercontent.com/17405609/27318336-baea2102-55c6-11e7-880f-cc3ebe1a24ed.png)

**Comment by tomoyuki1110** [comment]
・1706180070有本 千鶴i　Phone　safari

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました
