### ISSUE TITLE
バグ。デザインいれたのに真っ白になる

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#1014]
デザインをいれたはずなのに真っ白になってます。
・1706150053大塚湧一　iPhone　safari
![screenshot_20170620-144339](https://user-images.githubusercontent.com/17405609/27318372-de4948d0-55c6-11e7-91d1-7a51c15ebdab.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました
