### ISSUE TITLE
SSLの更新

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#1021]
ou have an AWS Certificate Manager (ACM) provided SSL/TLS certificate in your AWS account that expires on Sep 17, 2017 at 12:00:00 UTC. That certificate has the following domains:
up-t.jp, *.up-t.jp

AWS account ID: 898711982798
AWS Region name: ap-northeast-1
Certificate identifier: arn:aws:acm:ap-northeast-1:898711982798:certificate/64562ecc-199f-40a8-b480-0810a204f4f3

Therefore, ACM has initiated the renewal process for this certificate.

To complete the renewal of this certificate, the domain owners must use the approval link that was sent in separate validation request emails. Those emails were sent on Aug 03, 2017 at 12:25:43 UTC to the following addresses:
postmaster@up-t.jp, webmaster@up-t.jp, admin@up-t.jp, administrator@up-t.jp, hostmaster@up-t.jp, tomo.miyamoto@maruig.co.jp
The link in those emails is valid for 3 days from the time the emails were sent. If you do not use those links within 3 days, please go to the ACM console and resend the validation emails. You can find documentation on how to do so at https://aws.amazon.com/premiumsupport/knowledge-center/resend-email-ssl/

If the certificate is not renewed and the current certificate expires, your website might become unreachable.

追加案件：更新お願いします
また、今後の引き継ぎお願い致します。

If you have questions about this process, please use the Support Center at https://console.aws.amazon.com/support to contact AWS Support. If you don’t have an AWS support plan, post a new thread in the AWS Certificate Manager discussion forum at https://forums.aws.amazon.com/forum.jspa?forumID=206

This notification is intended solely for authorized individuals for up-t.jp. To express any concerns about this notification or if it has reached you in error, forward it along with a brief explanation of your concern to validation-questions@amazon.com.

**Comment by alexeypolitov** [comment]
@tomoyuki1110 更新済み
