### ISSUE TITLE
プレビュー画像と印刷画像が違う

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/up-t-web#1023]
up-tでプレビュー画像と印刷画像で異なる問題が出てます。

a) 1708210041　江口　祐一
　　プレビュー画像-aと印刷画像-bがズレる？
　　印刷画像で上に不要な線が入る(プレビュー画像では見えない)
プレビュー-a
![-a](https://user-images.githubusercontent.com/23730555/29762961-104b4af6-8c0c-11e7-92d4-07a08bebeaaf.png)
印刷画像-a
![-a](https://user-images.githubusercontent.com/23730555/29762969-14cabd32-8c0c-11e7-894a-d57b7e41c174.png)

b) 1708240049　ケイト 直子
　　プレビュー画像-bでは出ている文字が印刷画像-bで消えてしまう
プレビュー-b
![-b](https://user-images.githubusercontent.com/23730555/29763026-5f67f922-8c0c-11e7-8933-6ecad5730c30.png)
印刷画像-b
![-b](https://user-images.githubusercontent.com/23730555/29763048-7195cce6-8c0c-11e7-8e6f-c43df2d123bf.png)

**Comment by alexeypolitov** [comment]
@take-iwa 修正済みです
