### ISSUE TITLE
シルクではなかったときに、カートで文字とイラストの削除

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#1032]
![2017-10-06 14 50 25](https://user-images.githubusercontent.com/17405609/31264770-2ca5056c-aaa6-11e7-8b51-22bd2a4f5357.png)

削除してください。

**Comment by tomoyuki1110** [comment]
シルクではなかったときに、上記文言とイラストが出てしまうので、出ないようにお願い致します。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 削除しました
