### ISSUE TITLE
【緊急】アプリで数量とカラーが変更できないバグ

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#1034]
一番新しいバージョンでアプリの数量とカラーが変更できないバグがでているようです。
早急に対応お願いします。

**Comment by tomoyuki1110** [comment]
![screenshot_20171007-195422](https://user-images.githubusercontent.com/17405609/31307179-5f97dd48-ab99-11e7-92f0-6d43ca9f6301.png)
![screenshot_20171007-194034](https://user-images.githubusercontent.com/17405609/31307180-5fc1aede-ab99-11e7-91e6-0388b1c02e18.png)

数字やカラーがでてこない。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正済み
