### ISSUE TITLE
プリンティにアップロードしたらアップロード中のままになる

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#1044]
プリンティにアップロードしたらアップロード中のままになる

修正したとのことですが、
されてません

**Comment by alexeypolitov** [comment]
@tomoyuki1110 さっき確認してprinttyにアップできました。金曜日の時点で誰かcrontabでprinntyアップを停止しました。明日再確認ください。シルクスクリーンも含めてお願いします
