### ISSUE TITLE
デザイン変更お願いします

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#901]
![screenshot_20170411-220448](https://cloud.githubusercontent.com/assets/17405609/24916276/a6d06386-1f14-11e7-8604-aa47728c3e9d.png)
![2017-04-11 22 49 43](https://cloud.githubusercontent.com/assets/17405609/24916278/a7840e90-1f14-11e7-81f2-521242d89c2b.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 デザインを変更しました。ご確認ください
https://projects.invisionapp.com/d/main#/console/6174408/229442792/preview
