### ISSUE TITLE
ツールにGOOGLEANLYtiCSを入れて下さい。

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#914]
今入ってないので、スマホ、PCともに入れて下さい。

google analytics

maruiorimono1@gmail.com

orimonomarui1

インターネット事業部＝up-T=Up-tのデータ

ここのトラッキングを入れて下さい。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @hirokiokano 追加しました。キャッシュを空にしてご確認ください

**Comment by tomoyuki1110** [comment]
ソース見てますが、どこに入ってます？

**Comment by alexeypolitov** [comment]
@tomoyuki1110 AnalyticsでUP-T Drawerを選択してください

<img width="1439" alt="screen shot 2017-05-22 at 10 03 35" src="https://cloud.githubusercontent.com/assets/3468058/26288974/09a21a00-3ed6-11e7-9d53-c683594e9bed.png">
