### ISSUE TITLE
ツールデザイン：リバイス要望

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#979]
１．ボタンはできれば、横に並べないか（現在縦）
２．Otherをクリックしたらボタンが変わる
（今は、ボタンが出てきてボタンのみがでる。できれば、Tシャツなどを見せながらボタンを気軽に変更できるように
３．全削除がない

**Comment by alexeypolitov** [comment]
@tomoyuki1110 
> １．ボタンはできれば、横に並べないか（現在縦）
どの並びをすればいいですか？
> ２．Otherをクリックしたらボタンが変わる
（今は、ボタンが出てきてボタンのみがでる。できれば、Tシャツなどを見せながらボタンを気軽に変更できるように
tシャツ画面で出てくる問題は固定としています。その他のところで全ての機能があります

**Comment by alexeypolitov** [comment]
@tomoyuki1110 デザインを変更しました。ご確認ください
https://projects.invisionapp.com/d/main#/console/6174408/229442792/preview

**Comment by tomoyuki1110** [comment]
アイテム：はアイテム変更　としてください。

後は全てOkです。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 PC用なツールのデザインを変更しました。ご確認ください。
https://projects.invisionapp.com/d/main#/console/5873641/235139216/preview
