### ISSUE TITLE
スマホで日本語フォントを使用したとき切れる

### ISSUE THREAD

**Issue by hirokiokano** [DecodeLLC/up-t-web#981]
![591112488170d](https://cloud.githubusercontent.com/assets/17420901/25833306/3f300748-34ab-11e7-9746-60a86caf73ff.png)

**Comment by hirokiokano** [comment]
1705090013
で事象確認

**Comment by hirokiokano** [comment]
1705090078
こちらは日本語フォントで日本語を使っているのに切れています。
同じ原因でしょうか？
![default](https://cloud.githubusercontent.com/assets/17420901/25881962/e9b3f678-357a-11e7-8fbb-21361816651f.JPG)

**Comment by alexeypolitov** [comment]
@hirokiokano この２つは直せないですが調べられるようにログを追加しました。
