### ISSUE TITLE
英語フォントでもずれるケースがある

### ISSUE THREAD

**Issue by hirokiokano** [DecodeLLC/up-t-web#986]
1705100073栗田 充啓

![59131f6786c2e](https://cloud.githubusercontent.com/assets/17420901/26050041/2f24363e-3998-11e7-8d6d-1e08048c7635.png)
![img_11052017_143734_0](https://cloud.githubusercontent.com/assets/17420901/26050043/303fa7f6-3998-11e7-8bdc-eccf18acc9d5.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました。ご確認ください
