### ISSUE TITLE
各テキストが切れる現象が今だに起こっている

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#992]
PC
firefox
言語：日本語
入力文字：ブービー賞
フォント：通常フォント

iPhone
safari
言語：日本語
入力文字：第３回力設杯
通常フォント

PC
Microsoft Edge
言語：日本語
入力文字：「茶畑のシンデレラ！」
フォント：切絵字
言語：英語
入力文字：「KANAKO MOMOTA」
フォント：Broadband Regular

**Comment by alexeypolitov** [comment]
@tomoyuki1110 以前チャットでも聞いたけど、ここは何の問題がありますか？細かく教えていただけますか？
