### ISSUE TITLE
テキストが切れる現象

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/up-t-web#996]
![2017-05-31 14 33 06](https://cloud.githubusercontent.com/assets/17405609/26617103/2d9bf306-460e-11e7-9cbd-328d17cf114f.png)
商品番号：1705290030

![2017-05-31 14 33 11](https://cloud.githubusercontent.com/assets/17405609/26617102/2d9865b0-460e-11e7-8311-0516f0667142.png)

商品番号：1705290044

![2017-05-31 14 33 16](https://cloud.githubusercontent.com/assets/17405609/26617104/2dae5bb8-460e-11e7-83b7-8a1db2e60ed4.png)

**Comment by tomoyuki1110** [comment]
1705300034

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました。ご確認ください
